# PathError

``` python
f{self.name}{sig}
```



``` python
f{self.name}{sig}
```



Exception raised when a path is incorrect or can't be solved

Arguments
---------
- path (str) : incorrect path
- key (str) : key in the path
- incomplete (bool = False) : path is incomplete
- incorrect (bool = False) : path is incorrect


#### Arguments:
- **message**
- **path** (_str_) : incorrect path
- **key** (_str_ = None) : key in the path
- **incomplete** (_bool_ = False) : path is incomplete
- **incorrect** (_bool_ = False) : path is incorrect

### Inherited

BaseException.\_\_cause__ :black_small_square: BaseException.\_\_context__ :black_small_square: BaseException.\_\_delattr__ :black_small_square: BaseException.\_\_getattribute__ :black_small_square: BaseException.\_\_reduce__ :black_small_square: BaseException.\_\_repr__ :black_small_square: BaseException.\_\_setattr__ :black_small_square: BaseException.\_\_setstate__ :black_small_square: KeyError.\_\_str__ :black_small_square: BaseException.\_\_suppress_context__ :black_small_square: BaseException.\_\_traceback__ :black_small_square: BaseException.add_note :black_small_square: BaseException.args :black_small_square: BaseException.with_traceback :black_small_square: 



#### Arguments:
- **message**
- **path** (_str_) : incorrect path
- **key** (_str_ = None) : key in the path
- **incomplete** (_bool_ = False) : path is incomplete
- **incorrect** (_bool_ = False) : path is incorrect

### Inherited

BaseException.\_\_cause__ :black_small_square: BaseException.\_\_context__ :black_small_square: BaseException.\_\_delattr__ :black_small_square: BaseException.\_\_getattribute__ :black_small_square: BaseException.\_\_reduce__ :black_small_square: BaseException.\_\_repr__ :black_small_square: BaseException.\_\_setattr__ :black_small_square: BaseException.\_\_setstate__ :black_small_square: KeyError.\_\_str__ :black_small_square: BaseException.\_\_suppress_context__ :black_small_square: BaseException.\_\_traceback__ :black_small_square: BaseException.add_note :black_small_square: BaseException.args :black_small_square: BaseException.with_traceback :black_small_square: 

